from django.db import models

class GDP(models.Model):
    country = models.CharField(max_length=100)
    gdp2000 = models.FloatField(null=True, blank=True)
    gdp2001 = models.FloatField(null=True, blank=True)
    gdp2002 = models.FloatField(null=True, blank=True)
    gdp2003 = models.FloatField(null=True, blank=True)
    gdp2004 = models.FloatField(null=True, blank=True)
    gdp2005 = models.FloatField(null=True, blank=True)
    gdp2006 = models.FloatField(null=True, blank=True)
    gdp2007 = models.FloatField(null=True, blank=True)
    gdp2008 = models.FloatField(null=True, blank=True)
    gdp2009 = models.FloatField(null=True, blank=True)
    gdp2010 = models.FloatField(null=True, blank=True)
    gdp2011 = models.FloatField(null=True, blank=True)
    gdp2012 = models.FloatField(null=True, blank=True)
    gdp2013 = models.FloatField(null=True, blank=True)
    gdp2014 = models.FloatField(null=True, blank=True)
    gdp2015 = models.FloatField(null=True, blank=True)
    gdp2016 = models.FloatField(null=True, blank=True)
    gdp2017 = models.FloatField(null=True, blank=True)
    gdp2018 = models.FloatField(null=True, blank=True)
    gdp2019 = models.FloatField(null=True, blank=True)
    gdp2020 = models.FloatField(null=True, blank=True)
    gdp2021 = models.FloatField(null=True, blank=True)

class GDPR(models.Model):
    country = models.CharField(max_length=100)
    gdpr2000 = models.FloatField(null=True, blank=True)
    gdpr2001 = models.FloatField(null=True, blank=True)
    gdpr2002 = models.FloatField(null=True, blank=True)
    gdpr2003 = models.FloatField(null=True, blank=True)
    gdpr2004 = models.FloatField(null=True, blank=True)
    gdpr2005 = models.FloatField(null=True, blank=True)
    gdpr2006 = models.FloatField(null=True, blank=True)
    gdpr2007 = models.FloatField(null=True, blank=True)
    gdpr2008 = models.FloatField(null=True, blank=True)
    gdpr2009 = models.FloatField(null=True, blank=True)
    gdpr2010 = models.FloatField(null=True, blank=True)
    gdpr2011 = models.FloatField(null=True, blank=True)
    gdpr2012 = models.FloatField(null=True, blank=True)
    gdpr2013 = models.FloatField(null=True, blank=True)
    gdpr2014 = models.FloatField(null=True, blank=True)
    gdpr2015 = models.FloatField(null=True, blank=True)
    gdpr2016 = models.FloatField(null=True, blank=True)
    gdpr2017 = models.FloatField(null=True, blank=True)
    gdpr2018 = models.FloatField(null=True, blank=True)
    gdpr2019 = models.FloatField(null=True, blank=True)
    gdpr2020 = models.FloatField(null=True, blank=True)
    gdpr2021 = models.FloatField(null=True, blank=True)

class GDPP(models.Model):
    country = models.CharField(max_length=100)
    gdpp2000 = models.FloatField(null=True, blank=True)
    gdpp2001 = models.FloatField(null=True, blank=True)
    gdpp2002 = models.FloatField(null=True, blank=True)
    gdpp2003 = models.FloatField(null=True, blank=True)
    gdpp2004 = models.FloatField(null=True, blank=True)
    gdpp2005 = models.FloatField(null=True, blank=True)
    gdpp2006 = models.FloatField(null=True, blank=True)
    gdpp2007 = models.FloatField(null=True, blank=True)
    gdpp2008 = models.FloatField(null=True, blank=True)
    gdpp2009 = models.FloatField(null=True, blank=True)
    gdpp2010 = models.FloatField(null=True, blank=True)
    gdpp2011 = models.FloatField(null=True, blank=True)
    gdpp2012 = models.FloatField(null=True, blank=True)
    gdpp2013 = models.FloatField(null=True, blank=True)
    gdpp2014 = models.FloatField(null=True, blank=True)
    gdpp2015 = models.FloatField(null=True, blank=True)
    gdpp2016 = models.FloatField(null=True, blank=True)
    gdpp2017 = models.FloatField(null=True, blank=True)
    gdpp2018 = models.FloatField(null=True, blank=True)
    gdpp2019 = models.FloatField(null=True, blank=True)
    gdpp2020 = models.FloatField(null=True, blank=True)
    gdpp2021 = models.FloatField(null=True, blank=True)

class INVEST(models.Model):
    country = models.CharField(max_length=100)
    invest2000 = models.FloatField(null=True, blank=True)
    invest2001 = models.FloatField(null=True, blank=True)
    invest2002 = models.FloatField(null=True, blank=True)
    invest2003 = models.FloatField(null=True, blank=True)
    invest2004 = models.FloatField(null=True, blank=True)
    invest2005 = models.FloatField(null=True, blank=True)
    invest2006 = models.FloatField(null=True, blank=True)
    invest2007 = models.FloatField(null=True, blank=True)
    invest2008 = models.FloatField(null=True, blank=True)
    invest2009 = models.FloatField(null=True, blank=True)
    invest2010 = models.FloatField(null=True, blank=True)
    invest2011 = models.FloatField(null=True, blank=True)
    invest2012 = models.FloatField(null=True, blank=True)
    invest2013 = models.FloatField(null=True, blank=True)
    invest2014 = models.FloatField(null=True, blank=True)
    invest2015 = models.FloatField(null=True, blank=True)
    invest2016 = models.FloatField(null=True, blank=True)
    invest2017 = models.FloatField(null=True, blank=True)
    invest2018 = models.FloatField(null=True, blank=True)
    invest2019 = models.FloatField(null=True, blank=True)
    invest2020 = models.FloatField(null=True, blank=True)
    invest2021 = models.FloatField(null=True, blank=True)

class INFLATION(models.Model):
    country = models.CharField(max_length=100)
    inflation2000 = models.FloatField(null=True, blank=True)
    inflation2001 = models.FloatField(null=True, blank=True)
    inflation2002 = models.FloatField(null=True, blank=True)
    inflation2003 = models.FloatField(null=True, blank=True)
    inflation2004 = models.FloatField(null=True, blank=True)
    inflation2005 = models.FloatField(null=True, blank=True)
    inflation2006 = models.FloatField(null=True, blank=True)
    inflation2007 = models.FloatField(null=True, blank=True)
    inflation2008 = models.FloatField(null=True, blank=True)
    inflation2009 = models.FloatField(null=True, blank=True)
    inflation2010 = models.FloatField(null=True, blank=True)
    inflation2011 = models.FloatField(null=True, blank=True)
    inflation2012 = models.FloatField(null=True, blank=True)
    inflation2013 = models.FloatField(null=True, blank=True)
    inflation2014 = models.FloatField(null=True, blank=True)
    inflation2015 = models.FloatField(null=True, blank=True)
    inflation2016 = models.FloatField(null=True, blank=True)
    inflation2017 = models.FloatField(null=True, blank=True)
    inflation2018 = models.FloatField(null=True, blank=True)
    inflation2019 = models.FloatField(null=True, blank=True)
    inflation2020 = models.FloatField(null=True, blank=True)
    inflation2021 = models.FloatField(null=True, blank=True)

class IMPORT(models.Model):
    country = models.CharField(max_length=100)
    import2000 = models.FloatField(null=True, blank=True)
    import2001 = models.FloatField(null=True, blank=True)
    import2002 = models.FloatField(null=True, blank=True)
    import2003 = models.FloatField(null=True, blank=True)
    import2004 = models.FloatField(null=True, blank=True)
    import2005 = models.FloatField(null=True, blank=True)
    import2006 = models.FloatField(null=True, blank=True)
    import2007 = models.FloatField(null=True, blank=True)
    import2008 = models.FloatField(null=True, blank=True)
    import2009 = models.FloatField(null=True, blank=True)
    import2010 = models.FloatField(null=True, blank=True)
    import2011 = models.FloatField(null=True, blank=True)
    import2012 = models.FloatField(null=True, blank=True)
    import2013 = models.FloatField(null=True, blank=True)
    import2014 = models.FloatField(null=True, blank=True)
    import2015 = models.FloatField(null=True, blank=True)
    import2016 = models.FloatField(null=True, blank=True)
    import2017 = models.FloatField(null=True, blank=True)
    import2018 = models.FloatField(null=True, blank=True)
    import2019 = models.FloatField(null=True, blank=True)
    import2020 = models.FloatField(null=True, blank=True)
    import2021 = models.FloatField(null=True, blank=True)

class EXPORT(models.Model):
    country = models.CharField(max_length=100)
    export2000 = models.FloatField(null=True, blank=True)
    export2001 = models.FloatField(null=True, blank=True)
    export2002 = models.FloatField(null=True, blank=True)
    export2003 = models.FloatField(null=True, blank=True)
    export2004 = models.FloatField(null=True, blank=True)
    export2005 = models.FloatField(null=True, blank=True)
    export2006 = models.FloatField(null=True, blank=True)
    export2007 = models.FloatField(null=True, blank=True)
    export2008 = models.FloatField(null=True, blank=True)
    export2009 = models.FloatField(null=True, blank=True)
    export2010 = models.FloatField(null=True, blank=True)
    export2011 = models.FloatField(null=True, blank=True)
    export2012 = models.FloatField(null=True, blank=True)
    export2013 = models.FloatField(null=True, blank=True)
    export2014 = models.FloatField(null=True, blank=True)
    export2015 = models.FloatField(null=True, blank=True)
    export2016 = models.FloatField(null=True, blank=True)
    export2017 = models.FloatField(null=True, blank=True)
    export2018 = models.FloatField(null=True, blank=True)
    export2019 = models.FloatField(null=True, blank=True)
    export2020 = models.FloatField(null=True, blank=True)
    export2021 = models.FloatField(null=True, blank=True)

class UNEM(models.Model):
    country = models.CharField(max_length=100)
    unem2000 = models.FloatField(null=True, blank=True)
    unem2001 = models.FloatField(null=True, blank=True)
    unem2002 = models.FloatField(null=True, blank=True)
    unem2003 = models.FloatField(null=True, blank=True)
    unem2004 = models.FloatField(null=True, blank=True)
    unem2005 = models.FloatField(null=True, blank=True)
    unem2006 = models.FloatField(null=True, blank=True)
    unem2007 = models.FloatField(null=True, blank=True)
    unem2008 = models.FloatField(null=True, blank=True)
    unem2009 = models.FloatField(null=True, blank=True)
    unem2010 = models.FloatField(null=True, blank=True)
    unem2011 = models.FloatField(null=True, blank=True)
    unem2012 = models.FloatField(null=True, blank=True)
    unem2013 = models.FloatField(null=True, blank=True)
    unem2014 = models.FloatField(null=True, blank=True)
    unem2015 = models.FloatField(null=True, blank=True)
    unem2016 = models.FloatField(null=True, blank=True)
    unem2017 = models.FloatField(null=True, blank=True)
    unem2018 = models.FloatField(null=True, blank=True)
    unem2019 = models.FloatField(null=True, blank=True)
    unem2020 = models.FloatField(null=True, blank=True)
    unem2021 = models.FloatField(null=True, blank=True)

class POPU(models.Model):
    country = models.CharField(max_length=100)
    popu2000 = models.FloatField(null=True, blank=True)
    popu2001 = models.FloatField(null=True, blank=True)
    popu2002 = models.FloatField(null=True, blank=True)
    popu2003 = models.FloatField(null=True, blank=True)
    popu2004 = models.FloatField(null=True, blank=True)
    popu2005 = models.FloatField(null=True, blank=True)
    popu2006 = models.FloatField(null=True, blank=True)
    popu2007 = models.FloatField(null=True, blank=True)
    popu2008 = models.FloatField(null=True, blank=True)
    popu2009 = models.FloatField(null=True, blank=True)
    popu2010 = models.FloatField(null=True, blank=True)
    popu2011 = models.FloatField(null=True, blank=True)
    popu2012 = models.FloatField(null=True, blank=True)
    popu2013 = models.FloatField(null=True, blank=True)
    popu2014 = models.FloatField(null=True, blank=True)
    popu2015 = models.FloatField(null=True, blank=True)
    popu2016 = models.FloatField(null=True, blank=True)
    popu2017 = models.FloatField(null=True, blank=True)
    popu2018 = models.FloatField(null=True, blank=True)
    popu2019 = models.FloatField(null=True, blank=True)
    popu2020 = models.FloatField(null=True, blank=True)
    popu2021 = models.FloatField(null=True, blank=True)

class REVENUE(models.Model):
    country = models.CharField(max_length=100)
    revenue2000 = models.FloatField(null=True, blank=True)
    revenue2001 = models.FloatField(null=True, blank=True)
    revenue2002 = models.FloatField(null=True, blank=True)
    revenue2003 = models.FloatField(null=True, blank=True)
    revenue2004 = models.FloatField(null=True, blank=True)
    revenue2005 = models.FloatField(null=True, blank=True)
    revenue2006 = models.FloatField(null=True, blank=True)
    revenue2007 = models.FloatField(null=True, blank=True)
    revenue2008 = models.FloatField(null=True, blank=True)
    revenue2009 = models.FloatField(null=True, blank=True)
    revenue2010 = models.FloatField(null=True, blank=True)
    revenue2011 = models.FloatField(null=True, blank=True)
    revenue2012 = models.FloatField(null=True, blank=True)
    revenue2013 = models.FloatField(null=True, blank=True)
    revenue2014 = models.FloatField(null=True, blank=True)
    revenue2015 = models.FloatField(null=True, blank=True)
    revenue2016 = models.FloatField(null=True, blank=True)
    revenue2017 = models.FloatField(null=True, blank=True)
    revenue2018 = models.FloatField(null=True, blank=True)
    revenue2019 = models.FloatField(null=True, blank=True)
    revenue2020 = models.FloatField(null=True, blank=True)
    revenue2021 = models.FloatField(null=True, blank=True)

class COST(models.Model):
    country = models.CharField(max_length=100)
    cost2000 = models.FloatField(null=True, blank=True)
    cost2001 = models.FloatField(null=True, blank=True)
    cost2002 = models.FloatField(null=True, blank=True)
    cost2003 = models.FloatField(null=True, blank=True)
    cost2004 = models.FloatField(null=True, blank=True)
    cost2005 = models.FloatField(null=True, blank=True)
    cost2006 = models.FloatField(null=True, blank=True)
    cost2007 = models.FloatField(null=True, blank=True)
    cost2008 = models.FloatField(null=True, blank=True)
    cost2009 = models.FloatField(null=True, blank=True)
    cost2010 = models.FloatField(null=True, blank=True)
    cost2011 = models.FloatField(null=True, blank=True)
    cost2012 = models.FloatField(null=True, blank=True)
    cost2013 = models.FloatField(null=True, blank=True)
    cost2014 = models.FloatField(null=True, blank=True)
    cost2015 = models.FloatField(null=True, blank=True)
    cost2016 = models.FloatField(null=True, blank=True)
    cost2017 = models.FloatField(null=True, blank=True)
    cost2018 = models.FloatField(null=True, blank=True)
    cost2019 = models.FloatField(null=True, blank=True)
    cost2020 = models.FloatField(null=True, blank=True)
    cost2021 = models.FloatField(null=True, blank=True)

class AID_CHN(models.Model):
    donor = models.CharField(max_length=20)
    recipient = models.CharField(max_length=100)
    year = models.BigIntegerField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)

class AID_US(models.Model):
    donor = models.CharField(max_length=20)
    recipient = models.CharField(max_length=100)
    year = models.BigIntegerField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)

class EPU(models.Model):
    year = models.CharField(max_length=255)
    month = models.CharField(max_length=255)
    GEPU_current = models.FloatField(null=True, blank=True)
    GEPU_ppp = models.FloatField(null=True, blank=True)
    Australia = models.FloatField(null=True, blank=True)
    Brazil = models.FloatField(null=True, blank=True)
    Canada = models.FloatField(null=True, blank=True)
    Chile = models.FloatField(null=True, blank=True)
    China = models.FloatField(null=True, blank=True)
    Colombia = models.FloatField(null=True, blank=True)
    France = models.FloatField(null=True, blank=True)
    Germany = models.FloatField(null=True, blank=True)
    Greece = models.FloatField(null=True, blank=True)
    India = models.FloatField(null=True, blank=True)
    Ireland = models.FloatField(null=True, blank=True)
    Italy = models.FloatField(null=True, blank=True)
    Japan = models.FloatField(null=True, blank=True)
    Korea = models.FloatField(null=True, blank=True)
    Netherlands = models.FloatField(null=True, blank=True)
    Russia = models.FloatField(null=True, blank=True)
    Spain = models.FloatField(null=True, blank=True)
    Singapore = models.FloatField(null=True, blank=True)
    UK = models.FloatField(null=True, blank=True)
    US = models.FloatField(null=True, blank=True)
    Sweden = models.FloatField(null=True, blank=True)
    Mexico = models.FloatField(null=True, blank=True)
    Croatia = models.FloatField(null=True, blank=True)
    Belgium = models.FloatField(null=True, blank=True)
    Denmark = models.FloatField(null=True, blank=True)
    Pakistan = models.FloatField(null=True, blank=True)

class MODEL(models.Model):
    time = models.CharField(max_length=100)
    DEXPTR = models.FloatField(null=True, blank=True)
    DCPI = models.FloatField(null=True, blank=True)
    DGDPTR = models.FloatField(null=True, blank=True)
    DGOVTR = models.FloatField(null=True, blank=True)
    DIMPTR = models.FloatField(null=True, blank=True)
    DINVR = models.FloatField(null=True, blank=True)
    DRETR = models.FloatField(null=True, blank=True)

class RELATION(models.Model):
    time = models.CharField(max_length=100)
    export_total = models.FloatField(null=True, blank=True)
    import_total = models.FloatField(null=True, blank=True)
    export_Australia = models.FloatField(null=True, blank=True)
    import_Australia = models.FloatField(null=True, blank=True)
    export_Brazil = models.FloatField(null=True, blank=True)
    import_Brazil = models.FloatField(null=True, blank=True)
    export_France = models.FloatField(null=True, blank=True)
    import_France = models.FloatField(null=True, blank=True)
    export_Germany = models.FloatField(null=True, blank=True)
    import_Germany = models.FloatField(null=True, blank=True)
    export_India = models.FloatField(null=True, blank=True)
    import_India = models.FloatField(null=True, blank=True)
    export_Italy = models.FloatField(null=True, blank=True)
    import_Italy = models.FloatField(null=True, blank=True)
    export_Japan = models.FloatField(null=True, blank=True)
    import_Japan = models.FloatField(null=True, blank=True)
    export_Korea = models.FloatField(null=True, blank=True)
    import_Korea = models.FloatField(null=True, blank=True)
    export_Netherlands = models.FloatField(null=True, blank=True)
    import_Netherlands = models.FloatField(null=True, blank=True)
    export_Russia = models.FloatField(null=True, blank=True)
    import_Russia = models.FloatField(null=True, blank=True)
    export_US = models.FloatField(null=True, blank=True)
    import_US = models.FloatField(null=True, blank=True)
    export_UK = models.FloatField(null=True, blank=True)
    import_UK = models.FloatField(null=True, blank=True)

class RELATION_FOREIGN(models.Model):
    time = models.CharField(max_length=100)
    export_Australia = models.FloatField(null=True, blank=True)
    import_Australia = models.FloatField(null=True, blank=True)
    export_Brazil = models.FloatField(null=True, blank=True)
    import_Brazil = models.FloatField(null=True, blank=True)
    export_France = models.FloatField(null=True, blank=True)
    import_France = models.FloatField(null=True, blank=True)
    export_Germany = models.FloatField(null=True, blank=True)
    import_Germany = models.FloatField(null=True, blank=True)
    export_India = models.FloatField(null=True, blank=True)
    import_India = models.FloatField(null=True, blank=True)
    export_Italy = models.FloatField(null=True, blank=True)
    import_Italy = models.FloatField(null=True, blank=True)
    export_Japan = models.FloatField(null=True, blank=True)
    import_Japan = models.FloatField(null=True, blank=True)
    export_Korea = models.FloatField(null=True, blank=True)
    import_Korea = models.FloatField(null=True, blank=True)
    export_Netherlands = models.FloatField(null=True, blank=True)
    import_Netherlands = models.FloatField(null=True, blank=True)
    export_Russia = models.FloatField(null=True, blank=True)
    import_Russia = models.FloatField(null=True, blank=True)
    export_US = models.FloatField(null=True, blank=True)
    import_US = models.FloatField(null=True, blank=True)
    export_UK = models.FloatField(null=True, blank=True)
    import_UK = models.FloatField(null=True, blank=True)

class TO(models.Model):
    time = models.CharField(max_length=100)
    to_total = models.FloatField(null=True, blank=True)
    to_Australia = models.FloatField(null=True, blank=True)
    to_Brazil = models.FloatField(null=True, blank=True)
    to_France = models.FloatField(null=True, blank=True)
    to_Germany = models.FloatField(null=True, blank=True)
    to_India = models.FloatField(null=True, blank=True)
    to_Italy = models.FloatField(null=True, blank=True)
    to_Japan = models.FloatField(null=True, blank=True)
    to_Korea = models.FloatField(null=True, blank=True)
    to_Netherlands = models.FloatField(null=True, blank=True)
    to_Russia = models.FloatField(null=True, blank=True)
    to_US = models.FloatField(null=True, blank=True)
    to_UK = models.FloatField(null=True, blank=True)

class FROM(models.Model):
    time = models.CharField(max_length=100)
    from_total = models.FloatField(null=True, blank=True)
    from_Australia = models.FloatField(null=True, blank=True)
    from_Brazil = models.FloatField(null=True, blank=True)
    from_France = models.FloatField(null=True, blank=True)
    from_Germany = models.FloatField(null=True, blank=True)
    from_India = models.FloatField(null=True, blank=True)
    from_Italy = models.FloatField(null=True, blank=True)
    from_Japan = models.FloatField(null=True, blank=True)
    from_Korea = models.FloatField(null=True, blank=True)
    from_Netherlands = models.FloatField(null=True, blank=True)
    from_Russia = models.FloatField(null=True, blank=True)
    from_US = models.FloatField(null=True, blank=True)
    from_UK = models.FloatField(null=True, blank=True)
